[package]
name = "roverpics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"
reqwest = { version = "0.11.17", features = ["json"] }
serde = "1.0.162"
